# Generated by Django 2.2 on 2019-05-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted', models.FileField(upload_to='base/encrypted/%Y/%m/%d/')),
            ],
        ),
    ]
